In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
pre = pd.DataFrame({
    "1": [.080, .115, .050],
    "2": [.076, .113, .124],
    "3": [.086, .124, .051],
}, columns=["1", "2", "3"], index=["CEL", "JOD", "GAZ"])
pre

         1      2      3
CEL  0.080  0.076  0.086
JOD  0.115  0.113  0.124
GAZ  0.050  0.124  0.051

In [7]:
post = pd.DataFrame({
    "1": [.644, .093, .433],
    "2": [.067, .109, .408],
    "3": [.784, .105, .418],
}, columns=["1", "2", "3"], index=["CEL", "JOD", "GAZ"])
post

         1      2      3
CEL  0.644  0.067  0.784
JOD  0.093  0.109  0.105
GAZ  0.433  0.408  0.418

In [11]:
nasiak = 100*(post - pre)/pre  # %
nasiak

              1           2           3
CEL  705.000000  -11.842105  811.627907
JOD  -19.130435   -3.539823  -15.322581
GAZ  766.000000  229.032258  719.607843

In [21]:
df = pd.concat([nasiak.mean(axis=1), nasiak.std(axis=1)], axis=1)
df.columns = ["mean", "std"]
df

           mean         std
CEL  501.595267  447.834600
JOD  -12.664279    8.128144
GAZ  571.546700  297.531789